import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:habit_now/src/utils/models/task_model.dart';

List<CategoryModel> categories = [
  CategoryModel(
    color: const Color.fromARGB(255, 220, 21, 81),
    icon: Icons.timer_outlined,
    name: 'Task',
    id: '1',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 255, 89, 0),
    icon: Icons.block,
    name: 'Quit a bad habit',
    id: '2',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 167, 14, 60),
    icon: Icons.brush,
    name: 'Art',
    id: '3',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 4, 144),
    icon: Icons.self_improvement,
    name: 'Meditation',
    id: '4',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 53, 4, 159),
    icon: Icons.school,
    name: 'Study',
    id: '5',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 4, 105, 159),
    icon: Icons.directions_bike,
    name: 'Sports',
    id: '6',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 4, 159, 133),
    icon: Icons.local_activity,
    name: 'Entertainment',
    id: '7',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 4, 144),
    icon: Icons.speaker_notes,
    name: 'Social',
    id: '8',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 4, 159, 45),
    icon: Icons.speaker_notes,
    name: 'Social',
    id: '9',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 100, 159, 4),
    icon: Icons.attach_money_outlined,
    name: 'Finance',
    id: '10',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 4, 4),
    icon: Icons.add,
    name: 'Health',
    id: '11',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 4, 144),
    icon: Icons.work_outlined,
    name: 'Work',
    id: '12',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 100, 4),
    icon: Icons.restaurant_menu,
    name: 'Nurtrition',
    id: '13',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 4, 32, 159),
    icon: Icons.home,
    name: 'Home',
    id: '14',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 4, 159, 51),
    icon: Icons.filter_hdr,
    name: 'Outdoors',
    id: '15',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 159, 4, 14),
    icon: Icons.energy_savings_leaf_rounded,
    name: 'Energy',
    id: '16',
  ),
  CategoryModel(
    color: const Color.fromARGB(255, 118, 159, 4),
    icon: Icons.category,
    name: 'Other',
    id: '17',
  ),
];

List<IconData> customCategoriesIcons = [
  Icons.airline_seat_legroom_extra_sharp,
  Icons.baby_changing_station,
  Icons.airline_seat_recline_extra,
  Icons.snowmobile,
  Icons.sports_basketball_rounded,
  Icons.bakery_dining,
  Icons.self_improvement_outlined,
  Icons.transfer_within_a_station_sharp,
  Icons.sports_tennis_rounded,
  Icons.access_alarms_rounded,
  Icons.bed,
  Icons.bedtime_sharp,
  Icons.health_and_safety,
  Icons.sports_esports_rounded,
  Icons.supervisor_account,
  Icons.flight_sharp,
  Icons.yard,
  Icons.add_a_photo,
  Icons.checklist_rtl_sharp,
  Icons.baby_changing_station,
  Icons.airline_seat_recline_extra,
  Icons.snowmobile,
  Icons.sports_basketball_rounded,
  Icons.bakery_dining,
  Icons.self_improvement_outlined,
  Icons.transfer_within_a_station_sharp,
  Icons.sports_tennis_rounded,
  Icons.access_alarms_rounded,
  Icons.bed,
  Icons.bedtime_sharp,
  Icons.health_and_safety,
  Icons.sports_esports_rounded,
  Icons.supervisor_account,
  Icons.flight_sharp,
  Icons.yard,
  Icons.add_a_photo,
  Icons.checklist_rtl_sharp
];

List<Color> customCategoriesColors = [
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.pink,
  Colors.amber,
  Colors.white,
  Colors.orange,
  Colors.yellow,
  Colors.purple,
  Colors.lightGreenAccent,
  Colors.lightGreenAccent,
  Colors.deepOrange,
  Colors.deepPurpleAccent,
  Colors.lightGreenAccent,
  Colors.blueGrey,
];
